//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Strings", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to niebezpieczeństwo.
        /// </summary>
        internal static string danger {
            get {
                return ResourceManager.GetString("danger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wystąpił błąd.
        /// </summary>
        internal static string error_has_occurred {
            get {
                return ResourceManager.GetString("error_has_occurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plik został zaimportowany poprawnie.
        /// </summary>
        internal static string file_has_been_imported_successfully {
            get {
                return ResourceManager.GetString("file_has_been_imported_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to info.
        /// </summary>
        internal static string info {
            get {
                return ResourceManager.GetString("info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nie zaimplementowana funkcjonalność.
        /// </summary>
        internal static string not_implemented {
            get {
                return ResourceManager.GetString("not_implemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to problem z zaimportowaniem pliku.
        /// </summary>
        internal static string problem_with_import_excel_file {
            get {
                return ResourceManager.GetString("problem_with_import_excel_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sukces.
        /// </summary>
        internal static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to pole jest wymagane.
        /// </summary>
        internal static string this_field_is_required {
            get {
                return ResourceManager.GetString("this_field_is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uwaga.
        /// </summary>
        internal static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
    }
}
